<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
    body { font-family: DejaVu Sans, sans-serif; font-size: 11px; color: #222; }
    h1 { font-size: 16px; margin: 0 0 2px; }
    .meta { color: #666; font-size: 9px; margin-bottom: 10px; }
    table { width: 100%; border-collapse: collapse; margin-top: 8px; }
    th, td { border: 1px solid #ccc; padding: 4px 6px; text-align: left; }
    th { background: #f0f0f0; font-weight: bold; }
    .note { color: #b45309; font-size: 9px; margin-top: 8px; }
</style>
</head>
<body>
    <h1>{{ $title }}</h1>
    <div class="meta">
        Generated by {{ $generatedBy }} on {{ $generatedAt }}
        @if (count($filters))
            &mdash;
            @foreach ($filters as $key => $value)
                {{ ucfirst(str_replace('_', ' ', $key)) }}: {{ $value }}@if (! $loop->last), @endif
            @endforeach
        @endif
    </div>

    <table>
        <thead>
            <tr>
                @foreach ($columns as $column)
                    <th>{{ $column['label'] }}</th>
                @endforeach
            </tr>
        </thead>
        <tbody>
            @forelse ($rows as $row)
                <tr>
                    @foreach ($columns as $column)
                        <td>{{ data_get($row, $column['key']) ?? '' }}</td>
                    @endforeach
                </tr>
            @empty
                <tr><td colspan="{{ count($columns) }}">No records found.</td></tr>
            @endforelse
        </tbody>
    </table>

    @if ($truncated)
        <div class="note">Showing first {{ count($rows) }} of {{ $totalCount }} records. Export as Excel for the full data set.</div>
    @endif
</body>
</html>
