<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
    body { font-family: DejaVu Sans, sans-serif; font-size: 12px; color: #222; }
    .receipt { max-width: 380px; margin: 0 auto; border: 1px solid #ccc; padding: 16px 20px; }
    .brand { text-align: center; font-size: 18px; font-weight: bold; margin-bottom: 2px; }
    .subtitle { text-align: center; color: #666; font-size: 10px; margin-bottom: 14px; }
    .divider { border-top: 1px dashed #999; margin: 10px 0; }
    table.fields { width: 100%; border-collapse: collapse; }
    table.fields td { padding: 4px 0; vertical-align: top; }
    table.fields td.label { color: #666; width: 40%; }
    table.fields td.value { font-weight: bold; text-align: right; }
    .amount-row td { font-size: 15px; padding-top: 8px; }
    .footer { text-align: center; color: #888; font-size: 9px; margin-top: 14px; }
</style>
</head>
<body>
    <div class="receipt">
        <div class="brand">SunCash</div>
        <div class="subtitle">Transaction Receipt</div>
        <div class="divider"></div>
        <table class="fields">
            <tr><td class="label">Transaction ID</td><td class="value">{{ $data['transaction_id'] }}</td></tr>
            <tr><td class="label">Type</td><td class="value">{{ $data['transaction_type_label'] }}</td></tr>
            <tr><td class="label">Date</td><td class="value">{{ $data['timestamp'] }}</td></tr>
            <tr><td class="label">Customer</td><td class="value">{{ $data['customer_name'] ?: '—' }}</td></tr>
            <tr><td class="label">Mobile</td><td class="value">{{ $data['mobile'] ?: '—' }}</td></tr>
            <tr><td class="label">Status</td><td class="value">{{ $data['status_label'] ?? ucfirst($data['status']) }}</td></tr>
        </table>
        <div class="divider"></div>
        <table class="fields">
            <tr class="amount-row"><td class="label">Amount</td><td class="value">BSD {{ number_format($data['amount'], 2) }}</td></tr>
        </table>
        <div class="divider"></div>
        <div class="footer">Generated by {{ $generatedBy }} on {{ $generatedAt }}</div>
    </div>
</body>
</html>
